# Extensions bootstrap file.

[EXTENSIONS]
# Node manager.
https://github.com/ltdrdata/ComfyUI-Manager.git

# Utility nodes used by many community workflows.
https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git
https://github.com/crystian/ComfyUI-Crystools
https://github.com/cubiq/ComfyUI_essentials.git

# Resize and image utilities.
https://github.com/palant/image-resize-comfyui.git
https://github.com/giriss/comfy-image-saver.git
https://github.com/Sean-Bradley/ComfyUI-Image-Compare.git

# Grid output helper.
https://github.com/LEv145/images-grid-comfy-plugin.git